### ISSUE TITLE
Delete old static pages with useless tags

### ISSUE THREAD

**Issue by sylvainvivien** [Arachnid/bloggart#11] opened 2009-10-16 09:35 UTC
If a tag doesn't exist anymore, the static pages are still there with this path : tag/my_deleted_tag.

We can delete this tag after we publish a new post or add a "clean job" that delete all orpheans.

**Comment by Arachnid** [comment] 2009-10-16 09:43
Duplicate of issue 8.

**Closed as completed by Arachnid** 2009-10-16 09:43 UTC
