### ISSUE TITLE
Relative calls in {% extend %} is a bad practice

### ISSUE THREAD

**Issue by xen** [Arachnid/bloggart#31] opened 2009-10-25 14:00 UTC
In admin templates base.html call  {% extend "../base.html" %}. I'm try it with other Django version and its stop working. Seems like it is bad practice and you can't guaranty that it will work. So may be best way is divide admin and user templates or move both to same folder.

**Comment by Arachnid** [comment] 2009-10-25 21:49
Are you sure it's not just some other issue? Where did you see that it was bad practice?

**Comment by andialbrecht** [comment] 2009-10-26 13:29
I can confirm that relative paths don't work with Django 1.1. If you add

[sourcecode:python]
from google.appengine.dist import use_library
use_library('django', '1.1')
import django
from django import forms
django.newforms = forms
[/sourcecode]

to admin.py the admin pages fail with a TemplateSyntaxError because of a missing template (it's actually not a syntax error in the template).

But I think this problem only occurs if google.appengine.ext.webapp.template is used since the customized template loader in that module restricts the template paths to a single directory. When using the native Django template loader and renderer I had no problems.

**Comment by xen** [comment] 2009-10-26 21:30
Sorry for delay and thank to **andialbrecht**  for quick response. I'm tested locally with Django 1.1 and it was one of the issues, but only one with templates. Also I found that some other people have same problems here http://stackoverflow.com/questions/671369/django-specifying-a-base-template-by-directory

**Comment by Arachnid** [comment] 2009-10-26 23:26
Fixed with andialbrecht's patch.

**Closed as completed by Arachnid** 2009-10-26 23:26 UTC
